global:
  scrape_interval: 15s
  evaluation_interval: 15s

# Rule files specifies a list of globs. Rules and alerts are read from
# all matching files.
rule_files:
  - /etc/prometheus/rules.yml

scrape_configs:
  - job_name: prometheus1
    scrape_interval: 10s
    static_configs:
    - targets: [localhost:9090]
    # Usa autenticação básica para coletar as próprias métricas, visto que ela foi habilitada no servidor.
    basic_auth:
      username: 'rbb'
      password: 'rbb' # aqui pode ser usado <password_file>

  - job_name: federate
    scrape_interval: 15s

    honor_labels: true
    metrics_path: '/federate'

    params:
      'match[]':
        - '{job="prometheus2"}'
        - '{job="prometheus3"}'
        - '{__name__=~"job:.*"}'

    static_configs:
      - targets:
        - 'prometheus2.rbb.gov.br:9090'

    # A comunicação com o Prometheus 2 é criptografada e esse Prometheus precisa apresentar seu certificado
    # para ter acesso
    scheme: https
    tls_config:
      ca_file: tls/rbb.ca.cert
      cert_file: tls/rbb.prometheus1.cert
      key_file: tls/rbb.prometheus1.key

#alerting:
#  alertmanagers:
#    - static_configs:
#      - targets: [alertmanager.fabricdesenv.prodemge.gov.br:9093]