global:
  scrape_interval: 15s
  evaluation_interval: 15s

# Rule files specifies a list of globs. Rules and alerts are read from
# all matching files.
rule_files:
  - /etc/prometheus/rules.yml

scrape_configs:
  - job_name: prometheus3
    scrape_interval: 10s
    static_configs:
    - targets: [localhost:9090]

  # Métricas da rede Hyperledger Fabric
#  - job_name: ‘hyperledger_metrics’
#    scrape_interval: 10s
#    scheme: https
#    tls_config:
#      ca_file: tls/ca-cert.pem
#      cert_file: tls/cert.pem
#      key_file: tls/key.pem
#    static_configs:
#      - targets: [validator1.rbb.gov.br:9443, validator2.rbb.gov.br:9443]
